[game]
min = 1
max_turns = 9
digits = 4

# foo = [ "red", "yellow", "green",
#		"blue", "black", "pink"]
 foo = [ "â… ", "â…¡","â…¢", "â…£", "â…¤", "â…¥", "â…¦", "â…§", "â…¨" ]
# foo = [ "â‘ ", "â‘¡", "â‘¢", "â‘£", "â‘¤", "â‘¥", "â‘¦", "â‘§", "â‘¨" ]
# foo =[ "ğŸƒ", "ğŸƒ‚", "ğŸƒƒ", "ğŸƒ„", "ğŸƒ…", "ğŸƒ†", "ğŸƒ‡", "ğŸƒˆ", "ğŸƒ‰", "ğŸƒŠ", "ğŸƒ‹", "ğŸƒŒ", "ğŸƒ", "ğŸƒ", "ğŸƒ" ]

[UI]
use_gui = true
